### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by DiscoverProgramming** [DiscoverProgramming/CRUD-api#2]
My first issue.

**Comment by LyubomirT** [comment]
@DiscoverProgramming GitHub requires you to create actual issues for people to work on if you want to use the `collaborate` tag, instead of sample issues like this.

**Comment by DiscoverProgramming** [comment]
Thank you! I'm still learning how it all works, but I've completed many projects without contributing to the Community Exchange. First time for me. Thanks for letting me know.
